#!/bin/bash
####################
# Author - Robert E. Novak aka REN
#	sailnfool@gmail.com
#	skype:sailnfool.ren
#
# This script is obsolete by improvements to makefile and project
# scripts
#_____________________________________________________________________
# Rev.|Aut| Date     | Notes
#_____________________________________________________________________
# 2.0 |REN|11/13/2019| added vim directive and header file
# 1.0 |REN|09/06/2018| original version
#_____________________________________________________________________
#
####################
if [ -x "${__funcenv}" ]
then
	export __funcenv=1
	##################
	# The following are the environment variables created/modified
	# in stc.conf
	##################
	#	stcbindir=/usr/local/stc/bin
	#	stctmp=/tmp/stc
	#	stcfix="fix.sh"
	#	stcdebugtxt="debug.txt"
	##################
	# Set the BIN environment variable
	##################
	stcdir=${stcdir:-"/usr/var/stc"}
	stcbindir=${stcbindir:-"${stcdir}/bin"}
	export stcdir stcbindir
	
	##################
	# add the stcbindir to $PATH
	##################
	pathmunge ${stcbindir} after
	
	##################
	# This is the directory where stc commands will put 
	# temporary or diagnostic information.
	##################
	if [ -z "${stctmp}" ]
	then
		stctmp=/tmp/stc
	fi
	export stctmp
	mkdir -p ${stctmp}
	
	##################
	# The general usage of these next two variables is to use
	# them as suffixes for the files produced by an executing
	# command.  The files are usually placed in stctmp and
	# the command name is a prefix to the suffix.  There may
	# be other reasons to use the process ID (AKA $$) as part
	# of the name to avoid conflicts between multiple instances
	# of the utilities running on a single machine.
	##################
	# This is the suffix for scripts generated by stc utilities
	# Generally these utilities will unwind the actions of the 
	# parent script that ran the command - hence the "fix" in
	# the name
	##################
	stcfix=${stcfix:-"fix.sh"}
	export stcfix
	##################
	# This is the suffix for any debug or diagnostic information
	# generated by an stc utility
	##################
	stcdebugtxt=${stcdebugtxt:-"debug.txt"}
	export stcdebugtxt
fi # if [ -x "${__funcenv}" ]
# vim: set syntax=bash, lines=55, columns=120,colorcolumn=78
